version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: datascience-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: datascience2024
      MONGO_INITDB_DATABASE: dataprocessing
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - datascience-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: datascience-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:datascience2024@mongodb:27017/dataprocessing?authSource=admin
      FRONTEND_URL: http://localhost
      MAX_FILE_SIZE: 104857600
    ports:
      - "5000:5000"
    volumes:
      - backend_uploads:/app/uploads
      - backend_visualizations:/app/visualizations
    networks:
      - datascience-network
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: datascience-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - datascience-network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  datascience-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  backend_uploads:
    driver: local
  backend_visualizations:
    driver: local