version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: datascience-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: datascience2024
      MONGO_INITDB_DATABASE: dataprocessing
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - datascience-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: datascience-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:datascience2024@mongodb:27017/dataprocessing?authSource=admin
      FRONTEND_URL: http://localhost:3000
      MAX_FILE_SIZE: 104857600
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend_uploads:/app/uploads
      - backend_visualizations:/app/visualizations
    networks:
      - datascience-network
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: datascience-frontend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - datascience-network
    depends_on:
      - backend

networks:
  datascience-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  backend_uploads:
    driver: local
  backend_visualizations:
    driver: local